spring:
  application:
    name: mybatis
  profiles:
    active: dev
server:
  servlet:
    context-path: /api/v1
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000
config:
  otp:
    length: 6
    expiresOn: 900000 #15 min in milliseconds
