server:
  port: 8080
spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/mybatis
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml